server:
  port: 0

statsServiceId: stats-server

spring:
  application:
    name: compilation-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:65433/compilation-db
    driver-class-name: "org.postgresql.Driver"
    username: "compilation-db"
    password: "compilation_pw"