server:
  port: 0

spring:
  application:
    name: request-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:45432/request-db
    driver-class-name: "org.postgresql.Driver"
    username: "request-db"
    password: "request_pw"