application:
  name: gateway

spring:
  cloud:
    gateway:
      # для работы Gateway должен использовать Discovery Service
      discovery:
        locator:
          enabled: true
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/admin/**, /categories/**, /events/**, /compilations/**, /users/**

server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"